version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "Instalamos requirements"
      - pip install -r hello_world/requirements.txt -t hello_world/lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd hello_world/
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip app.py
  post_build:
    commands:
      - echo "Uploading zip to S3..."
      - aws s3 cp deployment_package.zip s3://pruebacodebuildjonatan
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name pruebasjonatan --zip-file fileb://deployment_package.zip
      - echo "DONE!!"  
